name: Pipeline de testes

on:
  push:
    branches:
      - feature**
jobs:
  ci-dotnet:
    uses: PePires58/ReusableWorkflows/.github/workflows/006_dotnet_build.yaml@main
    with: 
      dotnet-version: '8.0'
      working-directory: '.'